### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by mihneadb** [uberVU/dom-observer#2]
## Need

``` gherkin
As a JS dev
I want a clear and extensive README
So that I understand if domObserver is what I need
```
## Deliverables

A proper readme file.
## Solution

Write the readme.

**Comment by mihneadb** [comment]
@skidding just realised - I think it would be a good idea to also mention that the lib does not have any external dependencies. Wdyt? If ok, I can just add a quick follow-up commit to the README.

**Comment by ovidiuch** [comment]
Yup, in my experience people like that
