### ISSUE TITLE
Gh pages demo

### ISSUE THREAD

**Issue by mihneadb** [uberVU/dom-observer#3]
## Need

``` gherkin
As a JS dev
I want to see a quick demo of domObserver
So that I know if it's useful for my project
```
## Deliverables

A demo hosted on gh-pages.
## Solution

Write the demo.

TBD what it looks like.

**Comment by mihneadb** [comment]
I'm thinking something along the lines of:
- on one side, a list, to which the user can add, delete items and change their attributes
- on the other side, a "console" to which handlers log messages when the user interacts with the list
- maybe split the 2nd side and show both the handler's code and their log messages

Wdyt? Suggestions welcome!

cc @RadValentin @NiGhTTraX @skidding

**Comment by ovidiuch** [comment]
A simple way would be to encourage users to manipulate DOM directly from the browser console and in a simple box messages will show for each action they did. "Node added, node removed, etc." This way they get the feel that the observer works directly with the DOM so it's very easy to integrate in an existing project.

**Comment by mihneadb** [comment]
So should we force people to "get their hands dirty"? :D

On Tue, Jun 10, 2014 at 5:15 PM, Ovidiu Cherecheș notifications@github.com
wrote:

> A simple way would be to encourage users to manipulate DOM directly from
> the browser console and in a simple box messages will show for each action
> they did. "Node added, node removed, etc." This way they get the feel that
> the observer works directly with the DOM so it's very easy to integrate in
> an existing project.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uberVU/dom-observer/issues/3#issuecomment-45627289.

## 

[image: hootsuite] http://hootsuite.com

_Mihnea Dobrescu-Balaur_
Software Engineer | Hootsuite http://www.hootsuite.com
@mihneadb http://twitter.com/mihneadb
We are hiring in a _big_ way! Apply now http://hootsuite.com/careers

**Comment by ovidiuch** [comment]
Always, you need to _feel_ it to understand it ;)

**Comment by mihneadb** [comment]
:D ok!

On Tue, Jun 10, 2014 at 5:57 PM, Ovidiu Cherecheș notifications@github.com
wrote:

> Always, you need to _feel_ it to understand it ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uberVU/dom-observer/issues/3#issuecomment-45633483.

## 

[image: hootsuite] http://hootsuite.com

_Mihnea Dobrescu-Balaur_
Software Engineer | Hootsuite http://www.hootsuite.com
@mihneadb http://twitter.com/mihneadb
We are hiring in a _big_ way! Apply now http://hootsuite.com/careers
