### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by mihneadb** [uberVU/dom-observer#5]
We need to add a license, the project being open source.

cc @skidding

**Comment by ovidiuch** [comment]
cc @aismail what was the license Hootsuite agreed upon?

**Comment by aismail** [comment]
@skidding AFAIK apache2. This is what we have for hootvu and I know it was a major theme back then. https://github.com/uberVU/hootvu-app/blob/master/LICENSE

If you doubt that, you can always ask Noel.

**Comment by geordie** [comment]
Here is a simple example: https://github.com/hootsuite/statsd-client/blob/master/LICENSE

**Comment by mihneadb** [comment]
Thanks @geordie !
